### ISSUE TITLE
Memory pressure crash in Shuttles

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#426]
App runs out of memory after about ten minutes of looking at list of stops with map visible on iPhone. Memory crash on iPad as well if left alone for a few minutes. A quick look with Instruments doesn't show any obvious leaks, but Shuttles is definitely holding onto more memory than it needs to. Its footprint keeps growing with each route viewed, never shrinking by as much as you'd expect.

**Comment by Smartcop** [comment]
:+1:
