### ISSUE TITLE
Shuttles makes way more HTTP requests than necessary

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#429]
- /vehicles is called twice at start when only one call is needed.
- /predictions are fetched for all stops on active routes instead of just for the closest stops on those routes.
- Also, those /predictions calls aren’t being coalesced by agency. There should only ever need to be 2 /predictions calls for polling, one for `mit` and one for `charles-river`. See [the API documentation](http://mobile-dev.mit.edu/docs/modules/shuttles/api.html#get--shuttles-predictions-) for how you to build a single predictions URL that gets multiple route/stop combinations at once.
- When other modules are in front, Shuttles shouldn’t continue to make requests (unless the user signed up for an alert).

**Comment by Smartcop** [comment]
:+1:
