### ISSUE TITLE
Improve launch time responsiveness

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#44]
It can take a second or so for the app to become responsive when it is first launched. It would be nice if we could reduce that.

If it's not possible, we should probably add a splash screen back in to prevent users from being frustrated at things not responding to taps.

**Comment by Smartcop** [comment]
Everything except the iPhone 6 has a launch screen.

Needs a 1242 x 2208 pixel and a 2208 x 1242 pixel LaunchImage

**Comment by justinanderson** [comment]
We're not doing the 6 Plus until after 4.0, just up through the 6.
