### ISSUE TITLE
Open in Safari doesn't highlight on select

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#466]
Should have a row highlight when user taps on it.

**Comment by Smartcop** [comment]
@justinanderson Does this refer to "View in eProp Mobile"?

**Comment by justinanderson** [comment]
@Smartcop Yeah

**Comment by Smartcop** [comment]
Problem still exists on an iPad running iOS 8 in Scan Detail

**Comment by Smartcop** [comment]
@yevgmotov

**Comment by yevgmotov** [comment]
Should be fixed now.

**Comment by Smartcop** [comment]
:+1:
