### ISSUE TITLE
Scanner history unread count doesn't change

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#467]
When not in batch mode, scanning a code brings up the item detail but then also sets the unread indicator of the History button to 1, e.g. "History (1)". Because the scanned code is automatically viewed, the unread count shouldn't change when not in batch mode. Also, if the unread count is greater than 0, viewing that item in the history list should reset the unread count.

**Comment by Smartcop** [comment]
:+1:
