### ISSUE TITLE
Events on iPad Detail Cell Height

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#486]
When the recreateWebView is called the incorrect self.bounds is given.  I think this happens because the views are being setup in viewDidLoad because when you do select another cell and go back the webview has a correct height

Also I think newWebviewHeight should be newWebviewWidth.

**Comment by justinanderson** [comment]
There are better ways to do webview sizing in tableviews, but this is good enough for now.
