### ISSUE TITLE
Maps recents / suggestions missing icons

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#493]
Should have category / search / pin icons on left according to type of recent.

**Comment by justinanderson** [comment]
@LoganWright Should be using the pin_location and recent_search images from the assets in the dropbox. 
![pin_location](https://cloud.githubusercontent.com/assets/244952/5619916/8caa1c42-94f4-11e4-9594-85845daf1cbf.png)
![pin_location 2x](https://cloud.githubusercontent.com/assets/244952/5619921/8cb5b9c6-94f4-11e4-94bb-9fa2aee96d8a.png)
![pin_location 3x](https://cloud.githubusercontent.com/assets/244952/5619919/8caf31a0-94f4-11e4-908f-a03c7380cb06.png)
![recent_search](https://cloud.githubusercontent.com/assets/244952/5619918/8caf2bb0-94f4-11e4-8956-0354693433bf.png)
![recent_search 2x](https://cloud.githubusercontent.com/assets/244952/5619917/8caaeafa-94f4-11e4-9419-beef72c3fb8a.png)
![recent_search 3x](https://cloud.githubusercontent.com/assets/244952/5619920/8caf48a2-94f4-11e4-864c-c659dfa4bcfe.png)

**Comment by Smartcop** [comment]
:+1:
