### ISSUE TITLE
iPhone 6+ tours Introduction to MIT picture

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#600]
Is picture supposed to fill screen or center?
![screen shot 2014-12-18 at 6 33 36 pm](https://cloud.githubusercontent.com/assets/1474560/5497873/6372853a-86e4-11e4-9325-12c4da703d5d.png)

![screen shot 2014-12-18 at 6 32 54 pm](https://cloud.githubusercontent.com/assets/1474560/5497867/50a27c4e-86e4-11e4-8dc1-a731c5b4df9b.png)

**Comment by Smartcop** [comment]
@justinanderson 
image centered or full width?

**Comment by LoganWright** [comment]
@justinanderson - Right now, it's set to full width, but I also wrote code for centered and commented it out, so it's easy to switch if you'd like.

**Comment by justinanderson** [comment]
@Smartcop Full width

**Comment by Smartcop** [comment]
:+1:
