### ISSUE TITLE
iPad iOS 8 Scanner - Scan Detail Landscape

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#658]
Scanning in landscape mode.
Image is rotated 90 degrees in Scan Detail.

**Comment by Smartcop** [comment]
@yevgmotov

**Comment by yevgmotov** [comment]
Fixed.

**Comment by bskinner** [comment]
@yevgmotov When scanning in the UIInterfaceOrientationLandscapeLeft orientation, the image is rotated 180° (screenshot attached)

[Building Services - iPad 3 - Landscape Left](https://cloud.githubusercontent.com/assets/274456/5705913/c4520384-9a4a-11e4-8ac9-a25c5e95e20a.PNG)

**Comment by Smartcop** [comment]
:+1:
