### ISSUE TITLE
[Building Services] email field should not be validating the entered text

### ISSUE THREAD

**Issue by bskinner** [MIT-Mobile/MIT-Mobile-for-iPhone#665]
Current the email address being entered in the Building Services module is being validated. This should be a free-text field.

**Comment by yevgmotov** [comment]
@bskinner Just curious why do we have this requirement? And if having a valid email is not required, should it be required to enter any text in the email field for the form to be "submittable"?

**Comment by justinanderson** [comment]
@yevgmotov The people who get the submissions from the Building Services module made it a requirement that the email field be anything but empty. I know, it's a weird requirement.

**Comment by yevgmotov** [comment]
Thanks @justinanderson 

Fixed.
