### ISSUE TITLE
Tours - iPhone - disable rotation

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#666]
Tours - iPhone - disable rotation

**Comment by LoganWright** [comment]
@Smartcop -- Is there something specific you're noticing?  Tours is locked to portrait on my simulator/device from what I can tell.

**Comment by LoganWright** [comment]
Nevermind, I see it now on the stop detail screens.

**Comment by Smartcop** [comment]
:+1: 
@LoganWright Sorry about that, I'll improve on my issue descriptions in the future.
