### ISSUE TITLE
Shuttles - iPad first load no stop pins shown but buses are

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#680]
On first load of shuttles app buses are shown on map but stop pins don't show up unless a route is touched.  When loading shuttles any other time all the pins are shown

**Comment by rosslebeau** [comment]
Yep I noticed this and was just about to make a ticket myself.

**Comment by justinanderson** [comment]
I can't reproduce this anymore, so I'm going to say this is fixed.
