### ISSUE TITLE
Shuttles - iPad All Routes deselecting annotation zooms out

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#681]
When zooming in and selecting and then deselecting an annotation the map zooms all the way out to view all routes

**Comment by rosslebeau** [comment]
@Smartcop : I think that this behavior is desired in the case where the stop was selected from the left pane. It looks like in this issue, you mean when the user manually zooms/moves the map and taps on an annotation.

1. Is it true that this behavior is desired when selecting a stop from the left pane?
2. Is the appropriate fix for this issue to return the user to the map region they were viewing before selecting the stop (assuming stop selection moved the map)? Or is it to leave the map alone as long as they had manually moved/zoomed prior to selection?

**Comment by Smartcop** [comment]
@rosslebeau I was referring to manually zooming in on the map and tapping on the location.

@justinanderson --> questions

**Comment by justinanderson** [comment]
@rosslebeau We don't want the iPad map to pan and zoom when someone selects a stop from the left pane. It should just act as if the user tapped the pin.

I think auto-panning and zooming only makes sense for non-interactive maps like the small ones in the iPhone layout.

**Comment by Smartcop** [comment]
:+1:
