### ISSUE TITLE
iPad Building Services Urgent Issues Not clickable

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#682]
@justinanderson 
re: @yevgmotov 
The phone number and the email address are not clickable on the iPad.
Would you like for the phone number to call and the email address to open an email compose?
On the iPhone we have one button that opens up an action sheet.

![ios simulator screen shot jan 7 2015 6 55 11 pm](https://cloud.githubusercontent.com/assets/1474560/5655668/b9233064-969e-11e4-98d5-cd0475b3d688.png)

**Comment by Smartcop** [comment]
I've made a branch 3.6/experimental/building-services-urgent-actions which makes the phone and email labels into buttons performing the correct actions when selected.

**Comment by yevgmotov** [comment]
@Smartcop I can see a case with an email, but do we need a phone number to be a button on iPad? There's no phone application on iPad.

**Comment by Smartcop** [comment]
@yevgmotov You are correct.  Although the iPad can make phone calls using an iPhone on the same wifi we will hold this off until later.

**Comment by Smartcop** [comment]
:+1:
