### ISSUE TITLE
iPad Shuttles - Route Detail - Selecting a stop and then quickly scrolling the popover turns it into a blank table

### ISSUE THREAD

**Issue by LoganWright** [MIT-Mobile/MIT-Mobile-for-iPhone#687]
If you go to iPad shuttles home, select a route, like 'Tech Shuttle', then select a stop, we show a popover.  

Click away from this popover, then select a stop again so that a new popover appears.

If you quickly scroll the popover as soon as it appears, the tableview becomes blank.

**Comment by LoganWright** [comment]
Note: The issue is actually created by selecting a stop, and then selecting a second stop w/o closing the previous popover.

**Comment by Smartcop** [comment]
:+1:
