### ISSUE TITLE
iPad Shuttles All Routes - Rotating with popover open causes crashes

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#698]
iPad Shuttles All Routes - Rotating with popover open causes crashes

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MKMapAnnotationManager 0x7fd62010b7a0> for the key path "coordinate" from <MITShuttleStop 0x7fd62101c110> because it is not registered as an observer.'

**Comment by LoganWright** [comment]
@Smartcop  - I'm currently unable to reproduce this bug, here's what I'm doing.

Open iPad shuttles (tried iOS 7,8), tapping a stop, or selecting a stop from the left pane to bring up the stop popover.  Then I rotate a few times w/ no problems.

Are there more steps to reproduce this?

**Comment by Smartcop** [comment]
@LoganWright 
must have been a bad build I was on...
:+1:
