### ISSUE TITLE
iPad iOS 8.1 - Building Services Cannot Take Photo

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#701]
I cannot take a photo with building services.  Using branch 3.6/dev-yev-bugfixes.

Warning: Attempt to present <UIImagePickerController: 0x136108400>  on <UINavigationController: 0x135634120> which is already presenting (null)

**Comment by yevgmotov** [comment]
@Smartcop That's a good catch. Issue occurs on iOS8. Fixed.

**Comment by Smartcop** [comment]
:+1:
