### ISSUE TITLE
iPad iOS 8.1 Building Services upside down keyboard when holding iPad upside down

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#702]
![screen shot 2015-01-08 at 10 54 06 pm](https://cloud.githubusercontent.com/assets/1474560/5675316/4220e510-9789-11e4-873b-d53241a27e92.png)

**Comment by Smartcop** [comment]
@yevgmotov 
Make this a super low priority because it only happens if you lock the orientation before entering the app.

**Comment by Smartcop** [comment]
@yevgmotov 
/ happens when you switch from another module into this one but i don't think many people will still do that.

**Comment by yevgmotov** [comment]
@Smartcop can't even reproduce at the moment.

**Comment by Smartcop** [comment]
@yevgmotov 
This was on my iPad Air.  Are you using a physical device?

**Comment by yevgmotov** [comment]
@Smartcop Was testing on iPad mini. Is it reproducible for you every time you try?

**Comment by Smartcop** [comment]
:+1:
