### ISSUE TITLE
Disable drag from anywhere drawer gesture

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#703]
I'm finding myself accidentally opening the drawer when i mean to just tap on something or scroll down but start dragging with a little horizontal movement first. It'd be good to make the drawer only come out from a left edge swipes and from swipes on the left nav bar button, but not swipes starting anywhere on the screen.

**Comment by justinanderson** [comment]
@bskinner It's not cancelling or ceding control to other gesture recognizers. The Map module wasn't allowing edge swipes to open the drawer before, and I can now slide open the drawer horizontally and scroll the active module's table vertically in the same motion.

Also, is there a reason you didn't use UIScreenEdgePanGestureRecognizer?

**Comment by Smartcop** [comment]
@bskinner The dining hall menu comparison breaks this on iOS 7.  If you try to scroll <---- way the drawer starts to open too.
