### ISSUE TITLE
[Scanner] Setting focusPointOfInterest is not supported by iPad 2

### ISSUE THREAD

**Issue by bskinner** [MIT-Mobile/MIT-Mobile-for-iPhone#710]
When opening the Scanner module on an iPad 2, the app crashes in [-\[MITScannerMgr setupCaptureSession\]](https://github.com/MIT-Mobile/MIT-Mobile-for-iPhone/blob/3.6/dev-yev-bugfixes/Modules/QR%20Reader/MITScannerMgr.m#L72)

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Setting focusPointOfInterest is not supported by this device.  Use isFocusPointOfInterestSupported'
*** First throw call stack:
```

**Comment by yevgmotov** [comment]
Fixed.
