### ISSUE TITLE
Dining comparison view should use short names for venues

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#717]
Dining iPhone Landscape Calendar Howard Dining Text Cutoff
![screen shot 2015-01-12 at 4 13 33 pm](https://cloud.githubusercontent.com/assets/1474560/5711122/0872fa52-9a76-11e4-8585-cab5948c9d2e.png)

**Comment by justinanderson** [comment]
Dining should be using the short_name field for this screen. So "The Howard Dining Hall At Maseeh" would show up as "Maseeh".
