### ISSUE TITLE
iPad Shuttles callout not right

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#718]
It's using sticky footers and other odd things which the iPhone layout it's copying doesn't.

It should look like this:

![like-this](https://cloud.githubusercontent.com/assets/244952/5711651/21897dbe-9a7a-11e4-8ca8-f0910c842512.png)

Not this:

![not-this](https://cloud.githubusercontent.com/assets/244952/5711653/269c7afe-9a7a-11e4-92c8-ab63d2704ec2.png)

**Comment by LoganWright** [comment]
@justinanderson - I was able to change a few things and get the popover to much more closely resemble the mockups, with one main caveat.

It seems that the way SMCalloutView draws, it adds 20 px top and bottom padding and then masks this to accommodate the arrow.  This is generally unnoticeable, but when the arrow direction is down, the top Nav bar looks a little fatter than we'd prefer.  I'm not sure what it would take to fix this, but at first glance, it seems non-trivial.  

Let me know if the current implementation is acceptable when we merge it in, overall it looks considerably better in my opinion.

**Comment by LoganWright** [comment]
@justinanderson - I retract my previous comment, I was able to find a way to update the nav bar w/ minimal difficulty!

**Comment by LoganWright** [comment]
Pending iOS 8

**Comment by justinanderson** [comment]
:+1: Not perfect, but good enough for now. Callouts with the arrow on the top side occasionally, but not always, [have their content shifted down about 10 points](https://cloud.githubusercontent.com/assets/244952/5825196/88d03bdc-a0b7-11e4-9a3e-303a798ddee4.png).
