### ISSUE TITLE
Dining menus missing empty table message

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#721]
When a viewing the menu for a meal with no items, there should be a centered "[No Items](https://cloud.githubusercontent.com/assets/244952/5716433/61c40880-9abc-11e4-8692-8dad65c5e189.png)" message like we do for "No Bookmarks" or "No Results", since no items means only the regular food options are available for this meal.

There should be a separate "No Matching Items" if there's an active filter (gluten free, etc) but nothing matches.

**Comment by justinanderson** [comment]
:+1: This is good enough for now, though in the future we'll want to hide the placeholder row separators of the menu table. Should just be "No Items" floating on a white background.

**Comment by LoganWright** [comment]
@justinanderson - I made it a white background for this one while I was digging around w/ the other dining stuff, it was an easy fix.  It should be in the next PR.
