### ISSUE TITLE
Dining menu screen should handle days with no meals

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#726]
Dining halls with no meals on a day should still allow users to page to other days / meals. Should page by day instead of meals for the days that have no meals.

Looks like [this](https://cloud.githubusercontent.com/assets/244952/5716376/6fc2c828-9abb-11e4-9429-0ff855c6436f.png) right now, should look like [this](https://cloud.githubusercontent.com/assets/244952/5716386/d54abbec-9abb-11e4-8a52-ba51e7aeb944.png).

**Comment by Smartcop** [comment]
@LoganWright 
I was looking into this issue and it looks a little bit more complicated than expected.  Since you guys have worked on it, it might be easier for you guys to handle it.

**Comment by justinanderson** [comment]
:+1:
