### ISSUE TITLE
First launch of Dining Loading Indicator

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#734]
It would be nice to have a loading indicator on initial fetch of dining.  Looks broken having the 2 section headers and nothing else on the iPhone.  Also a loading indicator would be nice on the iPad.

 I restkit.network:RKObjectRequestOperation.m:220 GET 'https://m.mit.edu/apis/dining/' (200 OK / 1 objects) [request=7.2894s mapping=2.3079s total=9.6784s]

![ios simulator screen shot jan 13 2015 3 34 04 pm](https://cloud.githubusercontent.com/assets/1474560/5728625/9e50bde8-9b39-11e4-8240-e5172499d4e9.png)

**Comment by justinanderson** [comment]
:+1:
