### ISSUE TITLE
Shuttles 10 second delay on refresh of predictions when starting module

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#735]
When switching to the shuttles module, shuttle predictions are stale until 10 seconds later when the request is sent out to get new predictions.  Shuttle predictions should be updated sooner than this.

**Comment by justinanderson** [comment]
Note this is also a problem when switching between modules. If I look at Shuttles, switch to Emergency and wait 4 minutes, then switch back to Shuttles, it takes 10 seconds before Shuttles updates to new times. In the meantime it's showing stale predictions.

**Comment by justinanderson** [comment]
:+1:
