### ISSUE TITLE
libraries - iPhone - disable cell selection of book in Availability screen.

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#741]
Not a big issue but cell shows selection when selected and stays selected until touching somewhere else on the screen.

![ios simulator screen shot jan 14 2015 12 05 29 pm](https://cloud.githubusercontent.com/assets/1474560/5743180/a7232a9e-9be5-11e4-9a95-e1915c694d22.png)

**Comment by justinanderson** [comment]
Will be resolved by #761.

**Comment by Smartcop** [comment]
:+1:
