### ISSUE TITLE
Analyzing Project using Xcode -> Product -> Analyze

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#742]
There are a lot of missing calls to [super viewDidAppear] and similar calls in the project.

![analyzing](https://cloud.githubusercontent.com/assets/1474560/5743307/7c1f2978-9be6-11e4-8f53-9807044ebd6d.png)

**Comment by justinanderson** [comment]
:+1: There are other analyzer warnings as well, but those should be left for 4.0.1.
