### ISSUE TITLE
[Scanner] Intermittently fails to capture and save image

### ISSUE THREAD

**Issue by bskinner** [MIT-Mobile/MIT-Mobile-for-iPhone#746]
The Scanner module will occasionally fail to properly capture the scanned image, even though a code is detected and parsed. This occurs more often on newer devices.

**Comment by yevgmotov** [comment]
@bskinner Which devices have you tested with? iPhone 6/6+? I haven't encountered this issue in my testings but I only tested it with 5S and iPad Mini.

**Comment by justinanderson** [comment]
@yevgmotov Shows up a lot on an iPhone 6.

**Comment by yevgmotov** [comment]
@justinanderson Got it. Feel free to assign my way.

**Comment by bskinner** [comment]
It's a concurrency issue; the capture appears to be being canceled before the image is being captured. I just pushed up a fix. Should have a PR available momentarily for testing.
