### ISSUE TITLE
Dining - iPad - production - meal labels are null

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#748]
When starting app and going to dining module on production the meal labels (lunch, breakfast, dinner) are null.  They return to normal after selecting another meal and coming back.

![ios simulator screen shot jan 14 2015 3 39 05 pm](https://cloud.githubusercontent.com/assets/1474560/5747127/9368895e-9c03-11e4-94b6-fabe00d61e8e.png)

**Comment by Smartcop** [comment]
Note:  Tested before dinner and after brunch

**Comment by justinanderson** [comment]
:+1:
