### ISSUE TITLE
Dining house detail view shows a blank for hours

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iPhone#756]
Dining halls that are closed all day are showing nothing for that day's hours. It should say "Closed" where it would otherwise have say the name of the meal.

In [this screenshot](https://cloud.githubusercontent.com/assets/244952/5765671/68bac160-9cc9-11e4-9ae5-706e4764db06.png) "mon - sun" should be "Closed" instead of blank.

In [this screenshot](https://cloud.githubusercontent.com/assets/244952/5765703/b40ce260-9cc9-11e4-8c9e-b8bedb39e60c.png) "tue" and "thu - sun" should be "Closed" too, right aligned with Breakfast and Dinner.

**Comment by Smartcop** [comment]
[How is this?](https://cloud.githubusercontent.com/assets/1474560/5781183/904dffac-9d7e-11e4-9316-d09290d0be0b.png)

**Comment by justinanderson** [comment]
@Smartcop Works for me.

**Comment by Smartcop** [comment]
:+1:
