### ISSUE TITLE
[Scanner] No warning shown if camera configuration fails or is inaccessible

### ISSUE THREAD

**Issue by bskinner** [MIT-Mobile/MIT-Mobile-for-iPhone#757]
If the scanner in unable to access the camera (either due to a setup failure or lack of permission), only a black screen is displayed. The user should be notified that an error has occurred via an alert.

**Comment by yevgmotov** [comment]
@bskinner I just implemented the fix for this. But then noticed you took it over. It's a small fix, so I'll just shelve my changes.

**Comment by bskinner** [comment]
@yevgmotov If you've already got it fixed, feel free to push up the changes.

**Comment by yevgmotov** [comment]
@bskinner Sure
